"""
Transcription service using Whisper
Connects to local AI server for processing
"""

import requests
import json
from typing import Optional, Dict
from pathlib import Path


class TranscriptionService:
    """Handle audio transcription via local AI server"""

    def __init__(self, server_url: str = "http://localhost:11434"):
        """
        Initialize transcription service

        Args:
            server_url: URL of local AI server (Ollama or similar)
        """
        self.server_url = server_url
        self.whisper_endpoint = f"{server_url}/api/transcribe"

    def transcribe_audio(self, audio_path: str, language: str = "en") -> Dict[str, str]:
        """
        Transcribe audio file

        Args:
            audio_path: Path to audio file
            language: Language code (default: en)

        Returns:
            Dict with transcription text and metadata
        """
        if not Path(audio_path).exists():
            raise FileNotFoundError(f"Audio file not found: {audio_path}")

        # TODO: Implement actual connection to your office AI server
        # This is a placeholder for the server integration

        # For now, return mock response
        # Replace this with actual API call when server is ready
        return {
            "text": "[Transcription will be generated by your local AI server]",
            "language": language,
            "duration": 0.0,
            "segments": []
        }

    def transcribe_with_whisper_api(self, audio_path: str) -> str:
        """
        Transcribe using Whisper API endpoint

        This method will connect to your office server running Whisper
        Update the endpoint URL when ready to connect

        Args:
            audio_path: Path to audio file

        Returns:
            Transcribed text
        """
        try:
            with open(audio_path, 'rb') as audio_file:
                files = {'file': audio_file}
                response = requests.post(
                    self.whisper_endpoint,
                    files=files,
                    timeout=300  # 5 minute timeout for long recordings
                )

                if response.status_code == 200:
                    result = response.json()
                    return result.get('text', '')
                else:
                    raise Exception(f"Transcription failed: {response.status_code}")

        except requests.exceptions.ConnectionError:
            # Server not available yet
            print("AI server not connected. Using placeholder.")
            return "[Connect to office AI server for transcription]"

        except Exception as e:
            print(f"Transcription error: {e}")
            return f"[Transcription error: {str(e)}]"

    def save_transcription(self, text: str, output_path: str):
        """Save transcription to file"""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(text)
        print(f"Transcription saved to: {output_path}")


def transcribe_meeting_audio(audio_path: str, server_url: Optional[str] = None) -> str:
    """
    Convenience function to transcribe meeting audio

    Args:
        audio_path: Path to audio recording
        server_url: Optional custom server URL

    Returns:
        Transcribed text
    """
    service = TranscriptionService(server_url=server_url or "http://localhost:11434")
    return service.transcribe_with_whisper_api(audio_path)


if __name__ == "__main__":
    # Test transcription service
    service = TranscriptionService()
    print(f"Transcription service initialized")
    print(f"Server URL: {service.server_url}")
    print("Ready to connect to your office AI server")
